"use client";

import { useState, useEffect } from "react";
import { useDataContext } from "../../Dashboard/Context/DataContext";
import {
  Modal,
  TextInput,
  NumberInput,
  Select,
  Group,
  Button,
} from "@mantine/core";
import openPrintWindow from "../../components/print/printWindow";
import type { InvoiceData } from "../../components/print/printTemplate";

interface ReceiptVoucher {
  id: string;
  voucherNumber: string;
  voucherDate: Date;
  receivedFrom: string;
  receivedFromId?: string;
  amount: number;
  paymentMode: "Cash" | "Card" | "UPI" | "Cheque";
  reference: string;
  remarks: string;
  createdAt: Date;
}

export function ReceiptForm({
  open,
  onOpenChange,
  onSave,
  initialValues,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  onSave: (payload: ReceiptVoucher) => void;
  initialValues?: Partial<ReceiptVoucher>;
}) {
  const dataCtx = useDataContext();
  const customers = dataCtx?.customers ?? [];

  const [voucherNumber, setVoucherNumber] = useState("");
  const [voucherDate, setVoucherDate] = useState<string>(
    new Date().toISOString().slice(0, 10)
  );
  const [receivedFrom, setReceivedFrom] = useState("");
  const [receivedFromId, setReceivedFromId] = useState<string | undefined>(
    undefined
  );
  const [amount, setAmount] = useState<number | undefined>(undefined);
  const [paymentMode, setPaymentMode] =
    useState<ReceiptVoucher["paymentMode"]>("Cash");
  const [reference, setReference] = useState("");
  const [remarks, setRemarks] = useState("");

  // Reset or prefill form fields when modal is opened or initialValues change
  useEffect(() => {
    if (open) {
      setVoucherNumber(initialValues?.voucherNumber ?? "");
      setVoucherDate(
        initialValues?.voucherDate
          ? typeof initialValues.voucherDate === "string"
            ? (initialValues.voucherDate as string).slice(0, 10)
            : (initialValues.voucherDate as Date).toISOString().slice(0, 10)
          : new Date().toISOString().slice(0, 10)
      );
      setReceivedFrom(initialValues?.receivedFrom ?? "");
      setReceivedFromId(initialValues?.receivedFromId);
      setAmount(initialValues?.amount);
      setPaymentMode(initialValues?.paymentMode ?? "Cash");
      setReference(initialValues?.reference ?? "");
      setRemarks(initialValues?.remarks ?? "");
    }
  }, [open, initialValues]);

  function save() {
    onSave({
      id:
        typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
          ? crypto.randomUUID()
          : `rv-${Date.now()}`,
      voucherNumber,
      voucherDate: new Date(voucherDate),
      receivedFrom,
      receivedFromId,
      amount: Number(amount ?? 0),
      paymentMode,
      reference,
      remarks,
      createdAt: new Date(),
    });
    onOpenChange(false);
  }

  function printPreview() {
    const payload: InvoiceData = {
      title: "Receipt Voucher",
      companyName: "Seven Star Traders",
      addressLines: ["Nasir Gardezi Road, Chowk Fawara, Bohar Gate Multan"],
      invoiceNo: voucherNumber,
      date: voucherDate,
      items: [
        {
          sr: 1,
          section: `Received From: ${receivedFrom}`,
          amount: amount ?? 0,
        },
      ],
      totals: {
        subtotal: amount ?? 0,
        total: amount ?? 0,
        totalGrossAmount: amount ?? 0,
        totalDiscountAmount: 0,
        totalNetAmount: amount ?? 0,
      },
      footerNotes: ["Receipt generated by Aluminium POS"],
    };
    openPrintWindow(payload);
  }

  return (
    <Modal
      opened={open}
      onClose={() => onOpenChange(false)}
      title="Receipt Voucher"
    >
      <TextInput
        label="Voucher No"
        value={voucherNumber}
        onChange={(e) => setVoucherNumber(e.currentTarget.value)}
        placeholder="RV-2025-001"
      />
      <TextInput
        label="Date"
        type="date"
        value={voucherDate}
        onChange={(e) => setVoucherDate(e.currentTarget.value)}
      />

      <Select
        label="Received From"
        searchable
        clearable
        data={[
          ...customers.map((c) => ({ value: c._id, label: c.name })),
          { value: "__manual__", label: "Other (manual entry)" },
        ]}
        value={receivedFromId || (receivedFrom ? "__manual__" : null)}
        onChange={(v) => {
          if (v && v !== "__manual__") {
            const cust = customers.find((c) => c._id === v);
            setReceivedFromId(v);
            setReceivedFrom(cust?.name || "");
          } else {
            setReceivedFromId(undefined);
            setReceivedFrom("");
          }
        }}
        placeholder="Select customer or enter manually"
      />
      {(!receivedFromId || receivedFromId === "__manual__") && (
        <TextInput
          label="Manual Entry"
          value={receivedFrom}
          onChange={(e) => setReceivedFrom(e.currentTarget.value)}
          placeholder="Customer Name or Other"
        />
      )}

      <Group grow>
        <NumberInput
          label="Amount"
          value={amount}
          onChange={(v) => setAmount(typeof v === "number" ? v : undefined)}
        />
        <Select
          label="Payment Mode"
          data={["Cash", "Online/Bank"].map((v) => ({
            value: v,
            label: v,
          }))}
          value={paymentMode}
          onChange={(v) => setPaymentMode(v as ReceiptVoucher["paymentMode"])}
        />
        <TextInput
          label="Reference"
          value={reference}
          onChange={(e) => setReference(e.currentTarget.value)}
          placeholder="INV-2025-001"
        />
      </Group>

      <TextInput
        label="Remarks"
        value={remarks}
        onChange={(e) => setRemarks(e.currentTarget.value)}
        placeholder="Optional notes"
      />

      <Group justify="flex-end" mt="md">
        <Button variant="outline" onClick={() => onOpenChange(false)}>
          Cancel
        </Button>
        <Button variant="default" onClick={printPreview}>
          Print
        </Button>
        <Button onClick={save}>Save Receipt</Button>
      </Group>
    </Modal>
  );
}
